language: node_js
node_js:
  - 4
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - libpcap-dev
before_install:
  - export CC="gcc-4.9" CXX="g++-4.9"
